### ISSUE TITLE
点击＋按钮，选择U.S.语言的设定会丢失，显示空白。

### ISSUE THREAD

**Issue by wanyaxing** [dingmingxin/GhostSKB#1]
![image](https://cloud.githubusercontent.com/assets/7940795/16605055/ffa70e6c-435d-11e6-8e22-ae16f8645a8d.png)

**Comment by dingmingxin** [comment]
@wanyaxing  Mac OS X版本号多少？你用的哪个GhostSKB release版本，用最新的试试呢？

**Comment by wanyaxing** [comment]
MAC 10.11.5 (15F34)

**Comment by dingmingxin** [comment]
你那个中文输入法是什么？

**Comment by wanyaxing** [comment]
自带的拼音输入法。
话说，我其实只有两个输入法，选项里却有三个。

![image](https://cloud.githubusercontent.com/assets/7940795/16605145/284f808c-435f-11e6-88c7-3c8a393380dd.png)
![image](https://cloud.githubusercontent.com/assets/7940795/16605148/342baffc-435f-11e6-8873-16c19549b32c.png)

**Comment by dingmingxin** [comment]
空白是具体怎么出现的，请把详细步骤写一下。退出重进还存在么？

**Comment by wanyaxing** [comment]
一句两句说不清，我直接翻代码去了。
我觉得是这里的问题：
https://github.com/wanyaxing/GhostSKB/commit/e96d7fbd7d0cfcb592e50a94e1019bb72b65df05

**Comment by dingmingxin** [comment]
上面那个修改https://github.com/wanyaxing/GhostSKB/commit/e96d7fbd7d0cfcb592e50a94e1019bb72b65df05
不合适。抱歉我不能merge
