### ISSUE TITLE
bug反馈

### ISSUE THREAD

**Issue by maoxx241** [dingmingxin/GhostSKB#10]
作者你好，我是在app store上面下载的，电脑是带bar的mbp，系统是macOS Sierra, Version 10.12.3,输入法是自带的英文输入法加上百度输入法
安装了之后界面的颜色是黑色的底色，在安装之后可以添加和设置想要app的输入法，但是在重启之后出现了打不开界面的情况，并且在使用office word的时候无法切换输入法，请问什么时候可以修复这些bug，谢谢

**Comment by dingmingxin** [comment]
关于office word的说明，在https://github.com/dingmingxin/GhostSKB 已经有说明。这个程序对跨平台程序支持的不太好，原因是没有系统api可以提供做到的功能，也有可能是跨平台api没有调用我需要的系统通知接口。
