### ISSUE TITLE
切换搜狗输入法的问题

### ISSUE THREAD

**Issue by Asherlate** [dingmingxin/GhostSKB#11]
Hi , 最近刚开始使用 GhostSKB 感觉很好用，但是碰到一个和搜狗输入法的切换问题

目前 我的 搜狗输入法设置的是 默认中文输入, 但是 GhostSKB 自动切换 搜狗输入法后就会变成 英文输入

这种情况有解决办法吗

**Comment by dingmingxin** [comment]
我试了下搜狗输入法，没有复现这个问题。顺便看了下代码和系统提供的接口，这种情况出现了也不能解决，因为系统没有提供那么细粒度的接口，也可能是输入法有些自定义的行为导致的
