### ISSUE TITLE
无法启动，在menu bar上显示图标，但是点击后图标马上消失

### ISSUE THREAD

**Issue by nye17** [dingmingxin/GhostSKB#12]
系统是mac os sierra，我使用的是itunes上购买的版本，后来使用github上源程序自己在xcode上编译的版本出现同样问题。

程序安装后第一次使用时候好像没有问题，我设置了一些app的默认输入法，但是第二次打开就再也没成功过。

**Comment by nye17** [comment]
系统是mac os sierra，我使用的是itunes上购买的版本，后来使用github上源程序自己在xcode上编译的版本出现同样问题。

程序安装后第一次使用时候好像没有问题，我设置了一些app的默认输入法，但是第二次打开就再也没成功过。

**Comment by dingmingxin** [comment]
我提交了新的版本，1.3 ，你更新下试一试

**Comment by nye17** [comment]
谢谢！刚更新到了1.3，暂时使用好像没有问题。

**Comment by dingmingxin** [comment]
这个是由于设定好的app被删除以后，没处理好，导致的崩溃。一直是一小部分人在用，刚发现这个问题，谢谢
