### ISSUE TITLE
macosx 10.12.4 下不能工作

### ISSUE THREAD

**Issue by bcllemon** [dingmingxin/GhostSKB#13]
macosx 10.12.4,打开 app 并设置好之后, 切换程序,没有生效

**Comment by dingmingxin** [comment]
那个程序没生效？

**Comment by bcllemon** [comment]
对比了下, 升级系统后,需要重新设置一遍每个 App,才能生效. 目前对 Safari 无效.

**Comment by dingmingxin** [comment]
我的系统也是10.12.4 。对Safari是生效的。
