### ISSUE TITLE
dash 设置了英文但是没用

### ISSUE THREAD

**Issue by millionart** [dingmingxin/GhostSKB#14]
欧路词典也没用，更多情况发现中……

是我理解有误么？这个软件好像根本没用的：
比如我设置 QQ 使用中文输入法，但是我在 QQ 界面切换成英文，下次再打开 QQ 界面仍然是英文啊

**Comment by sherlockfff** [comment]
同，我的也没有用，iterm2用ghostskb设置了默认英文输入法，但是每次打开都是中文，用法理解有误？

**Comment by dingmingxin** [comment]
设置->键盘->输入法 , 把自动切换到文稿的输入法这一项取消勾选状态

**Comment by dingmingxin** [comment]
去AppStore下更新到最新版

**Comment by hidaghost** [comment]
刚才升级之后很多问题哟，emacs设置英文无响应，再次启动后emacs那个配置项消失，想再添加emacs弹出该项已在列表中，然而没有
另外微信设置为搜狗，再次启动应用后自动变为ABC…等等

**Comment by dingmingxin** [comment]
这次升级更新了数据的格式，需要重新设置。目前还有个问题，我今天刚解决。正在审核，这次更新之后就不会设置错乱的问题了。

**Comment by hidaghost** [comment]
我是卸载然后从AppStore重装了，重新配置之后还是不行…emacs不响应切换事件
微信现在是不管怎么设置都会切换到ABC
麻烦大佬啦~

**Comment by dingmingxin** [comment]
目前appstore 最新版本 是1.5， 正在审核的是1.6.1 ，审核通过了更新就没有之前的那些问题了。

**Comment by hidaghost** [comment]
已安装1.6.2版本，发现如下问题：
1. emacs 不响应切换，仍沿用上个应用的输入法状态，且在添加多个配置项时 emacs 的那项配置偶尔会自动发生输入法配置变更，在重启 ghostSKB 之后 emacs 配置项变成奇怪的状态 (emacs 图标消失，点击 '选择应用程序' 添加 emacs 时弹出该 app 已经在列表中)
2. 升级 ghostSKB 之后 微信不响应切换，从 AppStore 重装 ghostSKB 之后微信又能正常响应了，奇怪

系统版本 Sierra 10.12.5, emacs 版本 25.1.1
在 ghostSKB 升级到 1.5 之前 emacs 是能够响应切换的
还望解决，谢谢

**Comment by dingmingxin** [comment]
坑爹的app store缓存，虽然app store显示是1.6.2了，我下载下来一运行，还是老的包。不知道这个缓存能有多久会失效。我再加上版本信息更一下试试。

**Comment by dingmingxin** [comment]
@hidaghost @millionart 更新到1.6.3 了

**Comment by millionart** [comment]
上次发了反馈几天没有回复我就已经退款了，因为软件的功能和颜值都不能满足我
软件已卸载所以不必@我了
而且搜狗输入法已经有相关功能：高级——自动英文
如果之后有更高级的功能，我会考虑重新购买：

- 默认方案列表
- 指定输入法快捷键比如 fn+1 是英文 fn+2 是默认 fn+3 是搜狗这样
- 动态调整，根据某个 APP 最常使用的输入法确认下次的初始输入法

**Comment by dingmingxin** [comment]
各取所需 @millionart
