### ISSUE TITLE
Alfred 3 下生效？

### ISSUE THREAD

**Issue by leafonsword** [dingmingxin/GhostSKB#15]
我用的如下设置，其他app倒是好好地
![default](https://user-images.githubusercontent.com/1754580/27776175-d5d38788-5fda-11e7-8c53-33285ae7c1c8.png)

但是在Alfred 3下就是失效的
![default](https://user-images.githubusercontent.com/1754580/27776187-f66417e2-5fda-11e7-96cf-4af73ac7ddc5.png)

**Comment by dingmingxin** [comment]
目前是这样的，一小部分app不管用。alfred3 这个搜索框出现的时候，没有GhostSKB监听的那个消息，所以目前对这类App是无效的。我正在想办法解决这个问题。

**Comment by dingmingxin** [comment]
alfred 3 设置里自带了输入法设置。

**Comment by leafonsword** [comment]
@dingmingxin 那就关闭这个issue了
