### ISSUE TITLE
只有在重新获取Focus的时候才会切换输入法

### ISSUE THREAD

**Issue by 1461748123** [dingmingxin/GhostSKB#16]
用四指切换屏幕的时候不会自动切换输入法，需要让应用程序lose focus再重获focus才会生效

**Comment by dingmingxin** [comment]
谢谢反馈，我查一下这个问题。

**Comment by dingmingxin** [comment]
这个应用根据的就是截获的应用获得focus的消息来切换输入法的。所以这个不是问题。如果应用不在当前状态，也就没有必要针对性的切换输入法。
