### ISSUE TITLE
能不能换一个高清一点的菜单栏的图标

### ISSUE THREAD

**Issue by wangshuailong01** [dingmingxin/GhostSKB#19]
菜单栏的图标太模糊了，影响美观

**Comment by dingmingxin** [comment]
我的电脑还不是retina的，改天我调一下

**Comment by imhanjie** [comment]
对，retina 下显示太模糊了，所以每次更新后我都手动自己替换下才舒服点。

**Comment by dingmingxin** [comment]
@imhanjie 你有retina的尺寸么，给我发一个

**Comment by imhanjie** [comment]
@dingmingxin 我是每次直接把网易云音乐的那个黑色的❤️图标拿出来替换的（tiff格式的）http://pan.baidu.com/s/1kVwsUCf

**Comment by dingmingxin** [comment]
已经修复了这个问题了, 更新最新版1.6.7
