### ISSUE TITLE
希望能支持配置的导入导出

### ISSUE THREAD

**Issue by skywish** [dingmingxin/GhostSKB#20]
之前一直用的很习惯，但刚刚更新后发现上一个版本配置的app默认输入法清零了。
希望作者考虑一下版本更新后能保存上一个版本的配置，或者支持配置文件的导入导出功能。

**Comment by dingmingxin** [comment]
这是由于我废弃了以前的存储结构，用了一个比较轻量的数据结构。放心这种事以后不会发生了。不过，你提的这个点子挺不错，我考虑一下。

**Comment by dingmingxin** [comment]
最新版本已支持icloud同步配置文件
