### ISSUE TITLE
1.4之后，切换问题

### ISSUE THREAD

**Issue by PorUnaCabeza** [dingmingxin/GhostSKB#21]
作者你好，使用这款应用已经很长时间了，在前几天更新为1.4之后，出现了一点小问题，具体如下

#### 系统版本
10.12.4
#### 应用版本

| 应用                | 版本          |
| ------------- |:-------------:| 
| GhostSKB      | 1.4以上|
| Intellij idea     |2016.3.6 | 
| QQ                 |6.0.0| 

#### 应用设置

| 应用                | 输入法           |
| ------------- |:-------------:| 
| QQ                 |<kbd>搜狗拼音</kbd>|
| Intellij idea     |<kbd>英文ABC</kbd>| 
| iterm2            |<kbd>英文ABC</kbd>| 

##### 1
切换至QQ，输入法为<kbd>搜狗拼音</kbd>
再次切换至Intellij idea，输入法依然为<kbd>搜狗拼音</kbd>

##### 2
切换至iterm2，输入法为<kbd>英文ABC</kbd>
再次切换至Intellij idea，输入法依然为<kbd>英文ABC</kbd>

##### 3
经与其他应用的实验，发现Intellij idea会跟随上一个应用的输入法，但是在我的印象中，1.4以下版本是没有这个问题

谢谢

**Comment by dingmingxin** [comment]
1.6.3 最新版本。
