### ISSUE TITLE
Emacs 切换问题

### ISSUE THREAD

**Issue by hidaghost** [dingmingxin/GhostSKB#22]
已更新 ghostSKB 1.6.3
Emacs 25.2
1. 通过 Homebrew 安装 与 一般 APP 方式安装的 Emacs，都有在使用 cmd+tab 切换 与 光标切换 均没有响应输入法切换，只有从 Mission Control 切换才响应的问题
2. 通过 Homebrew 安装的 Emacs, 在添加配置项时只能从 应用程序目录下的软连接(Homebrew 安装的app 放在 /usr/local/opt 中) 添加，添加到配置项后表现有些古怪，重启 ghostSKB 之后配置项图标消失，能否在添加配置项时 新增一个 直接从路径添加？

**Comment by dingmingxin** [comment]
1.  mission control 切换的问题解决不了。
2. GhostSKB没有限制从哪个路径添加应用，这个是自由的。我自己也是用macports装的emacs，没有出现这个问题。

尝试以下步骤：
1. 卸载GhostSKB
2. rm -rf ~/Library/Containers/com.dmx.GhostSKB
再重新安装试试

**Comment by hidaghost** [comment]
我覆盖了 /Application 下的 Emacs.app，然后好了，看来是软连接的问题
建议是可以直接通过路径添加，finder 用着挺蛋疼…

**Comment by dingmingxin** [comment]
finder对普通用户友好，对程序员可能不入字符路径来的方便
