### ISSUE TITLE
itunes購買版本，使用一個月後不得不卸載

### ISSUE THREAD

**Issue by nye17** [dingmingxin/GhostSKB#23]
我一般就是在wechat，chrome，macvim，和iterm2四者之間切換，只有wechat需要中文，但是GhostSKB時好時壞，根本讓人摸不著規律，所以我仍然要經常小心翼翼的手工切換輸入法。不好意思，沒有辦法提供比較有建設性的反饋，唯一的感覺就是不好用，根本沒有達到各種app間的無縫切換。沒有辦法設施default的輸入法，而且每次update後設置的列表全部都消失了，很讓人沮喪。真心希望這個軟件在不遠的將來可以更有用，謝謝你起了個開頭。

**Comment by imhanjie** [comment]
其实 1 - 2 个月之前的版本一直都是好好的，很好用的。这几天疯狂更新了几次，我也出现了时好时坏的问题，希望作者赶紧 fix 下

**Comment by dingmingxin** [comment]
1.6.3 是最新稳定版本，经过反复测试，可以放心使用。

**Comment by nye17** [comment]
我使用就是刚更新的1.6.3。刚又重新安装测试了几次，在sierra 10.12.5下，chrome（默认英文）和wechat（默认中文）之间使用相互切换，wechat的中文输入切换回来后没有维持。

**Comment by imhanjie** [comment]
我也是 1.6.3 ，更新后规则都重新设置了，时好时坏。。。

**Comment by dingmingxin** [comment]
你们的系统版本，贴一下。还有，是哪个软件不管用，也烦请具体说一下。

**Comment by nye17** [comment]
Mac Sierra 10.12.5 (16F73)
Chrome Version 59.0.3071.115
Wechat 2.2.8 (8578)

**Comment by dingmingxin** [comment]
设置->键盘->输入法-> 自动切换东文稿的输入法。 这个取消勾选了么？

**Comment by imhanjie** [comment]
系统版本和上面的一样 10.12.5 的，刚刚试了几下，目前就发现微信时好时坏，其他的应用目前切换正常。

**Comment by imhanjie** [comment]
自动切换到文稿那个选项是关闭的

**Comment by nye17** [comment]
对的，按照文档要求一直是“取消勾选”的状态。我除了wechat之外完全不使用中文，所以对其他程序的好坏不了解。

**Comment by dingmingxin** [comment]
这就很奇怪了，我一直在用chrome和wechat，没有出现过这种问题。是不是还有别的软件再管理输入法，重启电脑后，只打开wechat和chrome试试切换管不管用呢。

**Comment by imhanjie** [comment]
我发现微信和QQ时好时坏了，刚刚测试的环境是 Chrome 和 QQ、微信互切出现的，Chrome 是 ABC，QQ 和 微信 是中文输入法

**Comment by dingmingxin** [comment]
这些问题已彻底解决，更新到1.6.7版本即可
