### ISSUE TITLE
在暗色菜单栏下颜色有点诡异。。

### ISSUE THREAD

**Issue by jx3fans** [dingmingxin/GhostSKB#26]
<img width="482" alt="default" src="https://user-images.githubusercontent.com/870076/32764164-0756c860-c93f-11e7-8478-de67a05981a7.png">

如图，在暗色菜单栏下颜色有点诡异。。

附暗色菜单栏开启方式：
系统偏好设置→通用→外观下面那个“使用暗色菜单栏和dock”复选框勾上。

**Comment by dingmingxin** [comment]
最新版1.6.9已解决这个问题，请更新
