### ISSUE TITLE
可以增加隐藏菜单栏图标的设置选项吗？多谢

### ISSUE THREAD

**Issue by erinsnow** [dingmingxin/GhostSKB#28]
一直在用，非常好用。就是习惯了清爽，可以不要常驻菜单栏吗？感谢开发者的劳动。

**Comment by dingmingxin** [comment]
如果隐藏了菜单栏图标，到时候想关闭这个应用或者像更改、增加设置了，该去哪打开呢？
有这样的应用么，麻烦告知一下，我看看是怎么做的。

**Comment by erinsnow** [comment]
PopClip

发自我的 iPhone

**Comment by dingmingxin** [comment]
最新版本已经可以隐藏菜单栏图标了。

**Comment by erinsnow** [comment]
66666

发自我的 iPhone
