### ISSUE TITLE
Wrong language when switching between telegram and slack

### ISSUE THREAD

**Issue by f3dm76** [dingmingxin/GhostSKB#29]
Not only them, but they are a stable reproducible example.
I have both slack and telegram in russian, and the rest in english. When I switch from slack to telegram by clicking on telegram window (which is visible from behind slack window), language changes to english. When I switch by selecting it in dock or by using Command+Shift everything is OK.
If you have trouble reproducing this, I can send video or help in any other way I can.

**Comment by dingmingxin** [comment]
Please update it to the newest version (1.7.0) from Mac App Store, to see if this problem had been solved.

**Comment by f3dm76** [comment]
Indeed it has been solved, thank you so much

2018-04-09 10:01 GMT+07:00 EverDing <notifications@github.com>:

**Comment by dingmingxin** [comment]
Thank you for you reply
