### ISSUE TITLE
chrome/vscode等都是无效的，iterm 也不稳定，只有微信切换中文时很稳定。

### ISSUE THREAD

**Issue by scottming** [dingmingxin/GhostSKB#35]

**Comment by 97world** [comment]
好像确实是微信客户端比较稳定, 其他都经常切换不过去

**Comment by scottming** [comment]
目前用 hammerspoon 切换配合这个一起后能用了。

**Comment by 97world** [comment]
@scottming 可以分享一下你是怎么配合使用的吗?😍

**Comment by 97world** [comment]
感谢 @scottming 告知了 hammerspoon 这款工具, 目前参照 https://dsdshcym.github.io/blog/2017/08/09/use-hammerspoon-to-auto-switch-input-methods/ 的最后一种 "Pure Hammerspoon" 方案, 无需 GhostSKB 即可实现自动切换输入法的功能.

**Comment by scottming** [comment]
嗯，是的，还有一些补充内容在emacs社区，你搜一下。
