### ISSUE TITLE
cannot open it in Mac OS 10.11

### ISSUE THREAD

**Issue by VoganWong** [dingmingxin/GhostSKB#4]
![image](https://cloud.githubusercontent.com/assets/13285922/16789195/0117824c-48de-11e6-848f-34fcb2b11e30.png)

**Comment by zhenpingfeng** [comment]
1.0.4在10.11.5遇到同样的问题

**Comment by zhenpingfeng** [comment]
换回1.0.3后，同样无法打开了。

**Comment by Arrow-Li** [comment]
设置里面安全性与隐私 选任何来源
GhostSKB打开了之后可以改回去

**Comment by VoganWong** [comment]
@Arrow-Li 本身就开着的 ![pic](http://ww1.sinaimg.cn/large/006tNbRwjw1f5sc1zgv52j31140u40vs.jpg)

**Comment by Arrow-Li** [comment]
刚试了一下的确不行
用终端可以打开
<img width="1090" alt="2016-07-13 16 24 08" src="https://cloud.githubusercontent.com/assets/17962902/16796633/4aaa6af4-4916-11e6-9b5f-e5c5df63e741.png">

**Comment by dingmingxin** [comment]
我重新上传了1.0.4 的release包，大家重新下载下试试。不行的话改天我用正式签名发到appstore去

**Comment by VoganWong** [comment]
@dingmingxin 仍旧打开失败。

**Comment by dingmingxin** [comment]
那暂且先用1.0.3 那个吧，等正式包出来之后我通知大家

**Comment by dingmingxin** [comment]
支持正版，青岛Mac AppStore 下载 https://itunes.apple.com/us/app/ghostskb/id1134384859?l=zh&ls=1&mt=12
