### ISSUE TITLE
早上更新系统后 没办法添加了…显示空白 没有加号

### ISSUE THREAD

**Issue by asker517** [dingmingxin/GhostSKB#5]

**Comment by dingmingxin** [comment]
@asker517  新系统版本号多少？用的最新版GhostSKB么？

**Comment by asker517** [comment]
@dingmingxin 系统版本号 10.11.6 早上才更新的 SKB是昨天AppStore下载的，现在打开就下面一个设置还有关闭按钮了，上面都是空白没办法 添加应用

**Comment by dingmingxin** [comment]
@asker517  我电脑升级到10.11.6 没有问题，试过别人的10.11.6也没问题。 你重启下试试呢？

**Comment by asker517** [comment]
@dingmingxin 并不能……我卸载了 重新安装了一次，还是空白 Orz

**Comment by dingmingxin** [comment]
这个应用并没有调用很复杂的系统接口，我测试过同事的好几台机器，也有10.11.6，真的没有出现你说的那个问题。如果实在不能使用，可以直接申请AppStore退款，取消购买

**Comment by asker517** [comment]
@dingmingxin 能给一下方便联系您的联系方式么
