### ISSUE TITLE
这是什么鬼?列表+去哪了,点-就崩溃

### ISSUE THREAD

**Issue by qx** [dingmingxin/GhostSKB#6]
![Uploading 屏幕截图 2016-08-17 11.16.31.png…]()

**Comment by qx** [comment]
appstore支持了下你,结果..哎

**Comment by dingmingxin** [comment]
@qx 截图没传上来，看不清啥问题
请问系统版本是多少。 用AppDelete 卸载再重新安装试试呢？

**Comment by qx** [comment]
@dingmingxin 你这个有很大问题,每次重启数据都会丢失,而且还找不到列表
![2016-08-23 08 57 09](https://cloud.githubusercontent.com/assets/648406/17876759/9d716b70-690f-11e6-8029-8982d3748bf1.png)

**Comment by dingmingxin** [comment]
Working on it. 后续会有新版本更新上去 @qx
