### ISSUE TITLE
Bug 反馈：切换程序时输入法偶尔切换失灵

### ISSUE THREAD

**Issue by cssmagic** [dingmingxin/GhostSKB#9]
在切换过程中，偶尔会保留上一个程序的输入法设置。

用系统快捷键或鼠标点击切换程序时都会发生。发生概率还挺高的，随便点几下就能重现。不知道是不是我电脑的个体问题。

Mac OS: 10.11.6
GhostSKB：1.1.3
输入法：U.S. 、QQ五笔、搜狗拼音

**Comment by dingmingxin** [comment]
某些程序自带了输入法的管理，就没办法了。比如微软的最新office套件就不好使
